version: "3.9"
services:
  ssql:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: sql
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./schemas:/var/lib/postgresql/data:rw
    networks:
      mysql_network:
        aliases:
          - sql_host
volumes:
  schemas:
networks:
  mysql_network:
    name: sql_net
    driver: bridge